import { executeQuery } from "@/lib/snowflake";
import type { CopilotResponse, CopilotCitation } from "@/lib/types";

const AGENT_FQN = "SENTINEL.RISK.SENTINEL_COPILOT";

type AgentContentBlock =
  | { type: "text"; text: string }
  | { type: "tool_use"; tool_use: { name: string; input: Record<string, unknown> } }
  | {
      type: "tool_result";
      tool_result: {
        name: string;
        status: string;
        content: { type: string; json: Record<string, unknown> }[];
      };
    }
  | { type: "suggested_queries"; suggested_queries: { query: string }[] };

type AgentResponse = {
  content: AgentContentBlock[];
  status: string;
  metadata?: Record<string, unknown>;
};

export type AgentResult = {
  response: CopilotResponse;
  toolsUsed: string[];
};

export async function askAgent(question: string): Promise<AgentResult> {
  const messagesJson = JSON.stringify({
    messages: [
      {
        role: "user",
        content: [{ type: "text", text: question }],
      },
    ],
  });

  const sql = `SELECT SNOWFLAKE.CORTEX.DATA_AGENT_RUN(?, ?) AS response`;
  const rows = await executeQuery<{ RESPONSE: string }>(sql, [AGENT_FQN, messagesJson]);

  if (!rows.length || !rows[0].RESPONSE) {
    return { response: fallback("Agent returned no response."), toolsUsed: [] };
  }

  const raw: AgentResponse = JSON.parse(rows[0].RESPONSE);

  if (raw.status !== "completed") {
    return { response: fallback("Agent did not complete successfully."), toolsUsed: [] };
  }

  const toolsUsed = extractToolsUsed(raw);
  return { response: parseAgentResponse(raw), toolsUsed };
}

function parseAgentResponse(raw: AgentResponse): CopilotResponse {
  const citations = new Map<string, CopilotCitation>();
  const sqlStatements: string[] = [];
  const caseIds = new Set<string>();
  const alertIds = new Set<string>();

  // DATA_AGENT_RUN can emit progress text between tool calls. The final user-facing
  // answer is the text emitted after the last tool result, so keep that section
  // instead of concatenating the agent's intermediate narration into the UI.
  let lastToolResultIndex = -1;
  raw.content.forEach((block, index) => {
    if (block.type === "tool_result") lastToolResultIndex = index;
  });

  const finalTextBlocks = raw.content
    .slice(lastToolResultIndex + 1)
    .filter((block): block is Extract<AgentContentBlock, { type: "text" }> => block.type === "text")
    .map((block) => block.text.trim())
    .filter(Boolean);

  const allTextBlocks = raw.content
    .filter((block): block is Extract<AgentContentBlock, { type: "text" }> => block.type === "text")
    .map((block) => block.text.trim())
    .filter(Boolean);

  const answer =
    finalTextBlocks.join("\n\n") ||
    allTextBlocks.at(-1) ||
    "Agent completed without a user-facing text response.";

  for (const block of raw.content) {
    if (block.type !== "tool_result") continue;

    const tr = block.tool_result;
    if (!tr.content) continue;

    let searchCitationAdded = false;

    for (const item of tr.content) {
      if (item.type !== "json" || !item.json) continue;
      const j = item.json as Record<string, unknown>;

      if (typeof j.sql === "string") {
        sqlStatements.push(j.sql);
        citations.set("sql:Cortex Analyst", {
          kind: "sql",
          label: "Cortex Analyst",
          detail: "Structured analytics generated by Cortex Analyst",
        });
      }

      if (
        !searchCitationAdded &&
        tr.name &&
        (tr.name.includes("search") || tr.name.includes("reg_doc") || tr.name.includes("call"))
      ) {
        citations.set(`doc:${tr.name}`, {
          kind: "doc",
          label: tr.name,
          detail: tr.status === "success" ? "Search completed" : tr.status,
        });
        searchCitationAdded = true;
      }
    }
  }

  const sql = sqlStatements.length
    ? sqlStatements.join("\n\n-- Next Cortex Analyst query --\n\n")
    : undefined;

  // Extract case and alert IDs from the answer text
  for (const m of answer.matchAll(/CASE-\d+/g)) caseIds.add(m[0]);
  for (const m of answer.matchAll(/ALR-\d+/g)) alertIds.add(m[0]);

  // Parse bullets from markdown list items
  const bullets: string[] = [];
  for (const line of answer.split("\n")) {
    const trimmed = line.trim();
    if (/^[-•*]\s+/.test(trimmed)) {
      bullets.push(trimmed.replace(/^[-•*]\s+/, ""));
    }
  }

  // Determine confidence based on agent completion and tool usage
  const usedTools = raw.content.some((b) => b.type === "tool_result");
  const confidence: CopilotResponse["confidence"] = usedTools ? "high" : "medium";

  // Check STR readiness
  const strReady =
    /\bSTR\b/i.test(answer) &&
    (caseIds.size > 0 || /filing|report|suspicious transaction/i.test(answer));

  return {
    answer,
    bullets,
    citations: [...citations.values()],
    sql,
    relatedCaseIds: [...caseIds],
    relatedAlertIds: [...alertIds],
    strReady: strReady || undefined,
    confidence,
  };
}

function extractToolsUsed(raw: AgentResponse): string[] {
  const tools = new Set<string>();
  for (const block of raw.content) {
    if (block.type === "tool_use") {
      tools.add(block.tool_use.name);
    }
    if (block.type === "tool_result") {
      if (block.tool_result.name) tools.add(block.tool_result.name);
    }
  }
  return [...tools];
}

function fallback(message: string): CopilotResponse {
  return {
    answer: message,
    bullets: [],
    citations: [],
    relatedCaseIds: [],
    relatedAlertIds: [],
    confidence: "low",
  };
}
