import type {
  Account,
  Alert,
  CaseFile,
  CreditMetric,
  Customer,
  LiquiditySnapshot,
  RegulatoryDoc,
  Transaction,
} from "@/lib/types";

export const INSTITUTION = {
  name: "Aarohan Finance Ltd.",
  type: "NBFC-ICC (deposit-taking)",
  cin: "U65923MH2014PTC261908",
  fiucode: "AFLIN0001",
  city: "Mumbai",
  regulator: "RBI",
  team: "Codeanigans",
  product: "Sentinel",
};

export const customers: Customer[] = [
  {
    id: "CUS-1042",
    name: "Rahul Mehta",
    type: "individual",
    pan: "BHGPM4421K",
    city: "Surat",
    kycStatus: "partial",
    pep: false,
    riskRating: "critical",
    occupation: "Diamond trader (self-declared)",
    onboardingDate: "2025-11-02",
  },
  {
    id: "CUS-1088",
    name: "Kavya Reddy",
    type: "individual",
    pan: "AWRPR8812P",
    city: "Hyderabad",
    kycStatus: "verified",
    pep: false,
    riskRating: "high",
    occupation: "Gig delivery partner",
    onboardingDate: "2026-03-14",
  },
  {
    id: "CUS-1089",
    name: "Imran Shaikh",
    type: "individual",
    pan: "CQWPS2290L",
    city: "Pune",
    kycStatus: "expired",
    pep: false,
    riskRating: "high",
    occupation: "Student",
    onboardingDate: "2026-04-02",
  },
  {
    id: "CUS-1090",
    name: "Neha Kulkarni",
    type: "individual",
    pan: "DPLPK7711Q",
    city: "Nashik",
    kycStatus: "partial",
    pep: false,
    riskRating: "high",
    occupation: "Homemaker",
    onboardingDate: "2026-04-11",
  },
  {
    id: "CUS-1101",
    name: "Hon. Vikram Desai",
    type: "individual",
    pan: "AAAPD9988C",
    city: "Ahmedabad",
    kycStatus: "verified",
    pep: true,
    riskRating: "high",
    occupation: "Former municipal corporator",
    onboardingDate: "2023-06-18",
  },
  {
    id: "CUS-1115",
    name: "Meru Logistics Pvt Ltd",
    type: "corporate",
    pan: "AALCM4410F",
    city: "Delhi",
    kycStatus: "verified",
    pep: false,
    riskRating: "high",
    occupation: "Road freight",
    onboardingDate: "2024-01-09",
  },
  {
    id: "CUS-1116",
    name: "Sagar Traders",
    type: "merchant",
    pan: "AAMFS2201H",
    city: "Delhi",
    kycStatus: "partial",
    pep: false,
    riskRating: "high",
    occupation: "Wholesale spices (related party of Meru)",
    onboardingDate: "2024-02-01",
  },
  {
    id: "CUS-1201",
    name: "Priya Nair",
    type: "individual",
    pan: "BTRPN3312J",
    city: "Kochi",
    kycStatus: "verified",
    pep: false,
    riskRating: "low",
    occupation: "Software engineer",
    onboardingDate: "2022-08-12",
  },
  {
    id: "CUS-1208",
    name: "Orbit Retail LLP",
    type: "corporate",
    pan: "AABFO8811R",
    city: "Bengaluru",
    kycStatus: "verified",
    pep: false,
    riskRating: "medium",
    occupation: "Apparel retail",
    onboardingDate: "2021-04-20",
  },
  {
    id: "CUS-1304",
    name: "Golden Peak Realty",
    type: "corporate",
    pan: "AADCG5520T",
    city: "Mumbai",
    kycStatus: "verified",
    pep: false,
    riskRating: "medium",
    occupation: "Real estate developer",
    onboardingDate: "2020-11-03",
  },
];

export const accounts: Account[] = [
  {
    id: "ACC-1042-01",
    customerId: "CUS-1042",
    product: "savings",
    ifsc: "AFLN0002144",
    openedOn: "2025-11-02",
    balanceInr: 48_20_000,
    status: "watch",
  },
  {
    id: "ACC-1088-01",
    customerId: "CUS-1088",
    product: "wallet",
    ifsc: "AFLN0003301",
    openedOn: "2026-03-14",
    balanceInr: 12_400,
    status: "frozen",
  },
  {
    id: "ACC-1089-01",
    customerId: "CUS-1089",
    product: "savings",
    ifsc: "AFLN0001188",
    openedOn: "2026-04-02",
    balanceInr: 8_900,
    status: "frozen",
  },
  {
    id: "ACC-1090-01",
    customerId: "CUS-1090",
    product: "savings",
    ifsc: "AFLN0004410",
    openedOn: "2026-04-11",
    balanceInr: 21_000,
    status: "watch",
  },
  {
    id: "ACC-1101-01",
    customerId: "CUS-1101",
    product: "current",
    ifsc: "AFLN0001001",
    openedOn: "2023-06-18",
    balanceInr: 1_12_40_000,
    status: "watch",
  },
  {
    id: "ACC-1115-01",
    customerId: "CUS-1115",
    product: "current",
    ifsc: "AFLN0000902",
    openedOn: "2024-01-09",
    balanceInr: 3_40_00_000,
    status: "watch",
  },
  {
    id: "ACC-1116-01",
    customerId: "CUS-1116",
    product: "current",
    ifsc: "AFLN0000903",
    openedOn: "2024-02-01",
    balanceInr: 88_00_000,
    status: "watch",
  },
  {
    id: "ACC-1201-01",
    customerId: "CUS-1201",
    product: "savings",
    ifsc: "AFLN0005512",
    openedOn: "2022-08-12",
    balanceInr: 6_40_000,
    status: "active",
  },
  {
    id: "ACC-1208-01",
    customerId: "CUS-1208",
    product: "loan",
    ifsc: "AFLN0002210",
    openedOn: "2021-04-20",
    balanceInr: -4_80_00_000,
    status: "active",
  },
  {
    id: "ACC-1304-01",
    customerId: "CUS-1304",
    product: "loan",
    ifsc: "AFLN0000108",
    openedOn: "2020-11-03",
    balanceInr: -186_00_00_000,
    status: "active",
  },
];

export const transactions: Transaction[] = [
  ...[1, 2, 3, 4, 5].map((i) => ({
    id: `TXN-STR-${i}`,
    ts: `2026-08-${20 + Math.min(i, 3)}T0${8 + i}:12:00+05:30`,
    accountId: "ACC-1042-01",
    counterparty: i % 2 ? "CASH-SURAT-BR14" : "UPI-UNKNOWN-HANDLE",
    channel: i % 2 ? ("CASH" as const) : ("UPI" as const),
    type: "credit" as const,
    amountInr: 9_40_000 + i * 8_000,
    city: "Surat",
    isFraud: true,
    typology: "structuring",
    narrative:
      "Cash/UPI credit just under ₹10 lakh CTR threshold. No invoice trail. Customer stated 'diamond lot settlement'.",
  })),
  {
    id: "TXN-STR-6",
    ts: "2026-08-24T19:40:00+05:30",
    accountId: "ACC-1042-01",
    counterparty: "HAWALA-LAYER-SING",
    channel: "IMPS",
    type: "debit",
    amountInr: 46_80_000,
    city: "Mumbai",
    isFraud: true,
    typology: "structuring",
    narrative: "Same-day outbound IMPS to a newly added beneficiary after five inbound credits.",
  },
  {
    id: "TXN-MULE-1",
    ts: "2026-08-28T02:11:00+05:30",
    accountId: "ACC-1088-01",
    counterparty: "NEXUS DIGITAL MART",
    channel: "NEFT",
    type: "credit",
    amountInr: 3_85_000,
    city: "Hyderabad",
    isFraud: true,
    typology: "mule",
    narrative: "Overnight inbound from a merchant later flagged in an industry mule list.",
  },
  {
    id: "TXN-MULE-2",
    ts: "2026-08-28T02:18:00+05:30",
    accountId: "ACC-1088-01",
    counterparty: "UPI-IMRAN-S",
    channel: "UPI",
    type: "debit",
    amountInr: 1_20_000,
    city: "Hyderabad",
    isFraud: true,
    typology: "mule",
    narrative: "Immediate split to fellow mule Imran Shaikh.",
  },
  {
    id: "TXN-MULE-3",
    ts: "2026-08-28T02:22:00+05:30",
    accountId: "ACC-1089-01",
    counterparty: "UPI-KAVYA-R",
    channel: "UPI",
    type: "credit",
    amountInr: 1_20_000,
    city: "Pune",
    isFraud: true,
    typology: "mule",
    narrative: "Inbound from Kavya within 11 minutes of her credit.",
  },
  {
    id: "TXN-MULE-4",
    ts: "2026-08-28T02:41:00+05:30",
    accountId: "ACC-1089-01",
    counterparty: "CASH-PUNE-ATM09",
    channel: "CASH",
    type: "debit",
    amountInr: 1_18_000,
    city: "Pune",
    isFraud: true,
    typology: "mule",
    narrative: "ATM cash-out of 98% of inbound funds.",
  },
  {
    id: "TXN-MULE-5",
    ts: "2026-08-28T03:05:00+05:30",
    accountId: "ACC-1090-01",
    counterparty: "NEXUS DIGITAL MART",
    channel: "IMPS",
    type: "credit",
    amountInr: 2_10_000,
    city: "Nashik",
    isFraud: true,
    typology: "mule",
    narrative: "Second hop of the same merchant credit.",
  },
  {
    id: "TXN-MULE-6",
    ts: "2026-08-28T03:16:00+05:30",
    accountId: "ACC-1090-01",
    counterparty: "CASH-NASHIK-BR2",
    channel: "CASH",
    type: "debit",
    amountInr: 1_95_000,
    city: "Nashik",
    isFraud: true,
    typology: "mule",
    narrative: "Branch cash withdrawal; KYC photo mismatch recorded by teller.",
  },
  {
    id: "TXN-PEP-1",
    ts: "2026-08-12T11:00:00+05:30",
    accountId: "ACC-1101-01",
    counterparty: "OVERSEAS-DUBAI-LLC",
    channel: "RTGS",
    type: "credit",
    amountInr: 78_00_000,
    city: "Ahmedabad",
    isFraud: false,
    typology: "pep_unusual",
    narrative: "Inward remittance labelled 'consultancy'. No contract on file.",
  },
  {
    id: "TXN-PEP-2",
    ts: "2026-08-15T16:20:00+05:30",
    accountId: "ACC-1101-01",
    counterparty: "LUXURY-AUTO-AHM",
    channel: "RTGS",
    type: "debit",
    amountInr: 42_00_000,
    city: "Ahmedabad",
    isFraud: false,
    typology: "pep_unusual",
    narrative: "Vehicle purchase inconsistent with declared income of ₹18L.",
  },
  {
    id: "TXN-RT-1",
    ts: "2026-08-18T10:00:00+05:30",
    accountId: "ACC-1115-01",
    counterparty: "Sagar Traders",
    channel: "NEFT",
    type: "debit",
    amountInr: 1_20_00_000,
    city: "Delhi",
    isFraud: true,
    typology: "round_trip",
    narrative: "Invoice for 'freight advance' to a related spice trader.",
  },
  {
    id: "TXN-RT-2",
    ts: "2026-08-19T09:30:00+05:30",
    accountId: "ACC-1116-01",
    counterparty: "Meru Logistics Pvt Ltd",
    channel: "NEFT",
    type: "debit",
    amountInr: 1_18_50_000,
    city: "Delhi",
    isFraud: true,
    typology: "round_trip",
    narrative: "Return of almost the same amount as 'goods return' within 24h.",
  },
  {
    id: "TXN-BENIGN-1",
    ts: "2026-08-29T09:12:00+05:30",
    accountId: "ACC-1201-01",
    counterparty: "SALARY-INFOSYS",
    channel: "NEFT",
    type: "credit",
    amountInr: 1_85_000,
    city: "Kochi",
    isFraud: false,
    narrative: "Monthly salary credit.",
  },
  {
    id: "TXN-BENIGN-2",
    ts: "2026-08-29T18:40:00+05:30",
    accountId: "ACC-1201-01",
    counterparty: "UPI-RENT-KOCHI",
    channel: "UPI",
    type: "debit",
    amountInr: 32_000,
    city: "Kochi",
    isFraud: false,
    narrative: "Recurring rent.",
  },
];

export const alerts: Alert[] = [
  {
    id: "ALRT-4410",
    ts: "2026-08-24T19:42:00+05:30",
    customerId: "CUS-1042",
    accountId: "ACC-1042-01",
    title: "Structuring just below CTR (₹10L)",
    typology: "structuring",
    score: 94,
    status: "escalated",
    caseId: "CASE-1042",
    explanation:
      "Five inbound credits of ₹9.4–9.7L in 72h, then a single outbound IMPS of ₹46.8L. Pattern matches smurfing against PMLA cash reporting.",
  },
  {
    id: "ALRT-4488",
    ts: "2026-08-28T03:20:00+05:30",
    customerId: "CUS-1088",
    accountId: "ACC-1088-01",
    title: "Overnight mule ring — cash-out velocity",
    typology: "mule",
    score: 97,
    status: "investigating",
    caseId: "CASE-1088",
    explanation:
      "Three low-income accounts received funds from Nexus Digital Mart after 02:00 IST and cashed out within 40 minutes. Shared device fingerprint on UPI.",
  },
  {
    id: "ALRT-4501",
    ts: "2026-08-15T16:25:00+05:30",
    customerId: "CUS-1101",
    accountId: "ACC-1101-01",
    title: "PEP lifestyle vs declared income",
    typology: "pep_unusual",
    score: 78,
    status: "open",
    caseId: "CASE-1101",
    explanation:
      "Politically exposed person received an unexplained Dubai credit and purchased a luxury vehicle. Enhanced due diligence overdue.",
  },
  {
    id: "ALRT-4515",
    ts: "2026-08-19T09:40:00+05:30",
    customerId: "CUS-1115",
    accountId: "ACC-1115-01",
    title: "Related-party round tripping",
    typology: "round_trip",
    score: 86,
    status: "investigating",
    caseId: "CASE-1115",
    explanation:
      "Meru Logistics and Sagar Traders share two directors. Funds looped with a 1.25% haircut in 23 hours.",
  },
  {
    id: "ALRT-4602",
    ts: "2026-08-30T08:05:00+05:30",
    customerId: "CUS-1304",
    accountId: "ACC-1304-01",
    title: "Credit concentration — CRE developer",
    typology: "credit_risk",
    score: 71,
    status: "open",
    explanation:
      "Golden Peak Realty is 11.4% of NBFC credit book. RBI large exposure norms for NBFCs require board reporting above 10%.",
  },
];

export const cases: CaseFile[] = [
  {
    id: "CASE-1042",
    title: "Rahul Mehta — CTR structuring",
    customerIds: ["CUS-1042"],
    status: "str_drafted",
    owner: "Ananya Iyer (AML L2)",
    openedOn: "2026-08-24",
    typology: "structuring",
    severity: "critical",
    summary:
      "Customer split cash/UPI inflows to stay under the ₹10 lakh cash transaction report, then layered outbound IMPS. STR draft is ready for FIU-IND.",
  },
  {
    id: "CASE-1088",
    title: "Nexus mule trio — Kavya / Imran / Neha",
    customerIds: ["CUS-1088", "CUS-1089", "CUS-1090"],
    status: "in_review",
    owner: "Rohit Banerjee (Fraud ops)",
    openedOn: "2026-08-28",
    typology: "mule",
    severity: "critical",
    summary:
      "Coordinated mule cash-out after 02:00 IST. Accounts frozen. STR recommended as a network filing, not three isolated SARs.",
  },
  {
    id: "CASE-1101",
    title: "PEP Vikram Desai — unexplained wealth",
    customerIds: ["CUS-1101"],
    status: "in_review",
    owner: "Meera Shah (EDD)",
    openedOn: "2026-08-15",
    typology: "pep_unusual",
    severity: "high",
    summary:
      "Source of funds for Dubai inward remittance not established. RBI KYC Master Direction requires ongoing EDD for PEPs.",
  },
  {
    id: "CASE-1115",
    title: "Meru ↔ Sagar round trip",
    customerIds: ["CUS-1115", "CUS-1116"],
    status: "new",
    owner: "Ananya Iyer (AML L2)",
    openedOn: "2026-08-19",
    typology: "round_trip",
    severity: "high",
    summary:
      "Related-party loop with thin invoices. Possible trade-based money laundering / books dressing ahead of a working-capital drawdown.",
  },
];

export const regulations: RegulatoryDoc[] = [
  {
    id: "DOC-PMLA-12",
    title: "PMLA Rules — Cash Transaction Reports",
    source: "Prevention of Money-laundering (Maintenance of Records) Rules, 2005",
    clause: "Rule 3 r/w Rule 8",
    topic: "CTR / structuring",
    excerpt:
      "Every reporting entity shall maintain a record of all cash transactions of the value of more than ten lakh rupees or its equivalent in foreign currency, whether as a single transaction or several integrally connected transactions.",
  },
  {
    id: "DOC-RBI-KYC-54",
    title: "RBI Master Direction — KYC (PEPs)",
    source: "RBI/DBR/2015-16/18 Master Direction – KYC Direction, 2016 (updated)",
    clause: "Chapter VII — PEPs",
    topic: "PEP / EDD",
    excerpt:
      "REs shall have appropriate risk management systems to determine whether a customer or beneficial owner is a politically exposed person. Ongoing due diligence on PEP relationships shall be subject to enhanced monitoring.",
  },
  {
    id: "DOC-FIU-STR",
    title: "FIU-IND — Suspicious Transaction Report",
    source: "FIU-IND reporting format (FINNet 2.0)",
    clause: "STR grounds of suspicion",
    topic: "STR filing",
    excerpt:
      "An STR shall be filed promptly, and in any case not later than seven working days from arriving at a finding of suspicion, irrespective of the amount of transaction or attempted transaction.",
  },
  {
    id: "DOC-RBI-NBFC-LE",
    title: "RBI Scale Based Regulation — Large Exposures",
    source: "RBI SBR for NBFCs",
    clause: "Large exposure / concentration",
    topic: "credit concentration",
    excerpt:
      "NBFCs shall put in place a board-approved policy on exposure norms. Single borrower / group exposures and sectoral concentration (including commercial real estate) shall be monitored against internal caps and reported to the Board.",
  },
  {
    id: "DOC-BASEL-LCR",
    title: "Basel III — Liquidity Coverage Ratio",
    source: "Basel Committee / RBI LCR framework for NBFCs in upper layer",
    clause: "LCR ≥ 100%",
    topic: "liquidity",
    excerpt:
      "The Liquidity Coverage Ratio is designed to ensure that banks hold a sufficient reserve of high-quality liquid assets to survive a significant stress scenario lasting 30 calendar days. RBI has extended graded LCR to upper-layer NBFCs.",
  },
  {
    id: "DOC-RBI-AML-MULE",
    title: "RBI / IBA guidance on mule accounts",
    source: "RBI circulars on digital fraud and mule accounts (2024–26)",
    clause: "Customer due diligence + rapid freeze",
    topic: "mule",
    excerpt:
      "Regulated entities shall implement velocity, device, and network analytics to detect mule behaviour, freeze suspected accounts on a best-effort basis, and file STRs where funds appear to be proceeds of cyber-enabled fraud.",
  },
];

export const liquidity: LiquiditySnapshot = {
  asOf: "2026-08-30",
  lcrPct: 108.4,
  nsfrPct: 104.1,
  hqlAInrCr: 642,
  wholesaleRunoffInrCr: 118,
  bufferDays: 34,
};

export const credit: CreditMetric = {
  asOf: "2026-08-30",
  totalRwaInrCr: 4_860,
  cet1Pct: 12.1,
  npaPct: 3.8,
  top20ConcentrationPct: 28.6,
  realEstateExposurePct: 19.4,
};

export const callTranscripts = [
  {
    id: "CALL-1042",
    customerId: "CUS-1042",
    ts: "2026-08-23T17:10:00+05:30",
    text: "Branch RM: Sir, these cash credits are just under ten lakh. Compliance will ask. Customer: Tell them diamond lots, cash is how Surat works. I will take the money out tomorrow. Do not freeze.",
  },
  {
    id: "CALL-1088",
    customerId: "CUS-1088",
    ts: "2026-08-27T21:44:00+05:30",
    text: "Inbound WhatsApp voice note (transcribed): Bro send the UPI to Imran first then Neha. ATM after 2. If bank calls say I sold my old scooty.",
  },
  {
    id: "CALL-1101",
    customerId: "CUS-1101",
    ts: "2026-08-14T12:02:00+05:30",
    text: "Relationship manager: Sir we need the consultancy contract for the Dubai credit. Customer: It is a family arrangement. Do not escalate. I will send something next week.",
  },
];
