-- Sentinel risk mart for Aarohan Finance (synthetic NBFC)
-- Run in the Snowflake worksheet that came with your hackathon credentials.
-- Then follow coco/PROMPTS.md so CoCo creates the semantic view, search service, and agent.

CREATE DATABASE IF NOT EXISTS SENTINEL;
CREATE SCHEMA IF NOT EXISTS SENTINEL.RISK;
CREATE WAREHOUSE IF NOT EXISTS SENTINEL_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE DATABASE SENTINEL;
USE SCHEMA RISK;
USE WAREHOUSE SENTINEL_WH;

CREATE OR REPLACE TABLE CUSTOMERS (
  CUSTOMER_ID STRING,
  NAME STRING,
  TYPE STRING,
  PAN STRING,
  CITY STRING,
  KYC_STATUS STRING,
  PEP BOOLEAN,
  RISK_RATING STRING,
  OCCUPATION STRING,
  ONBOARDING_DATE DATE
);

CREATE OR REPLACE TABLE ACCOUNTS (
  ACCOUNT_ID STRING,
  CUSTOMER_ID STRING,
  PRODUCT STRING,
  IFSC STRING,
  OPENED_ON DATE,
  BALANCE_INR NUMBER(18,2),
  STATUS STRING
);

CREATE OR REPLACE TABLE TRANSACTIONS (
  TXN_ID STRING,
  TXN_TS TIMESTAMP_TZ,
  ACCOUNT_ID STRING,
  CUSTOMER_ID STRING,
  COUNTERPARTY STRING,
  CHANNEL STRING,
  TXN_TYPE STRING,
  AMOUNT_INR NUMBER(18,2),
  CITY STRING,
  IS_FRAUD BOOLEAN,
  TYPOLOGY STRING,
  NARRATIVE STRING
);

CREATE OR REPLACE TABLE ALERTS (
  ALERT_ID STRING,
  ALERT_TS TIMESTAMP_TZ,
  CUSTOMER_ID STRING,
  ACCOUNT_ID STRING,
  TITLE STRING,
  TYPOLOGY STRING,
  SCORE NUMBER(5,2),
  STATUS STRING,
  CASE_ID STRING,
  EXPLANATION STRING
);

CREATE OR REPLACE TABLE CASES (
  CASE_ID STRING,
  TITLE STRING,
  STATUS STRING,
  OWNER STRING,
  OPENED_ON DATE,
  TYPOLOGY STRING,
  SEVERITY STRING,
  SUMMARY STRING
);

CREATE OR REPLACE TABLE CALL_TRANSCRIPTS (
  CALL_ID STRING,
  CUSTOMER_ID STRING,
  CALL_TS TIMESTAMP_TZ,
  TRANSCRIPT_TEXT STRING
);

CREATE OR REPLACE TABLE REG_DOCS (
  DOC_ID STRING,
  TITLE STRING,
  SOURCE STRING,
  CLAUSE STRING,
  TOPIC STRING,
  EXCERPT STRING
);

CREATE OR REPLACE TABLE LIQUIDITY_DAILY (
  AS_OF DATE,
  LCR_PCT FLOAT,
  NSFR_PCT FLOAT,
  HQLA_INR_CR FLOAT,
  WHOLESALE_RUNOFF_INR_CR FLOAT,
  BUFFER_DAYS NUMBER
);

CREATE OR REPLACE TABLE CREDIT_EXPOSURES (
  CUSTOMER_ID STRING,
  CUSTOMER_NAME STRING,
  EXPOSURE_INR NUMBER(18,2),
  SECTOR STRING
);

CREATE OR REPLACE TABLE COPILOT_AUDIT (
  AUDIT_ID STRING,
  ASKED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  USER_NAME STRING,
  QUESTION STRING,
  ANSWER STRING,
  CONFIDENCE STRING,
  CITATIONS STRING,
  SQL_TEXT STRING
);

-- Enable change tracking for Cortex Search
ALTER TABLE CALL_TRANSCRIPTS SET CHANGE_TRACKING = TRUE;
ALTER TABLE REG_DOCS SET CHANGE_TRACKING = TRUE;

-- Seed a minimum viable set (CoCo can generate the rest — see coco/PROMPTS.md)
INSERT INTO CUSTOMERS VALUES
('CUS-1042','Rahul Mehta','individual','BHGPM4421K','Surat','partial',FALSE,'critical','Diamond trader','2025-11-02'),
('CUS-1088','Kavya Reddy','individual','AWRPR8812P','Hyderabad','verified',FALSE,'high','Gig delivery partner','2026-03-14'),
('CUS-1089','Imran Shaikh','individual','CQWPS2290L','Pune','expired',FALSE,'high','Student','2026-04-02'),
('CUS-1090','Neha Kulkarni','individual','DPLPK7711Q','Nashik','partial',FALSE,'high','Homemaker','2026-04-11'),
('CUS-1101','Hon. Vikram Desai','individual','AAAPD9988C','Ahmedabad','verified',TRUE,'high','Former municipal corporator','2023-06-18'),
('CUS-1115','Meru Logistics Pvt Ltd','corporate','AALCM4410F','Delhi','verified',FALSE,'high','Road freight','2024-01-09'),
('CUS-1116','Sagar Traders','merchant','AAMFS2201H','Delhi','partial',FALSE,'high','Wholesale spices','2024-02-01'),
('CUS-1304','Golden Peak Realty','corporate','AADCG5520T','Mumbai','verified',FALSE,'medium','Real estate developer','2020-11-03');

INSERT INTO LIQUIDITY_DAILY VALUES ('2026-08-30', 108.4, 104.1, 642, 118, 34);

INSERT INTO CREDIT_EXPOSURES VALUES
('CUS-1304','Golden Peak Realty', 1860000000, 'CRE'),
('CUS-1208','Orbit Retail LLP', 48000000, 'RETAIL');

CREATE OR REPLACE CORTEX SEARCH SERVICE REG_DOC_SEARCH
  ON EXCERPT
  ATTRIBUTES TITLE, TOPIC, CLAUSE, SOURCE
  WAREHOUSE = SENTINEL_WH
  TARGET_LAG = '1 hour'
  AS (SELECT DOC_ID, TITLE, TOPIC, CLAUSE, SOURCE, EXCERPT FROM REG_DOCS);

CREATE OR REPLACE CORTEX SEARCH SERVICE CALL_SEARCH
  ON TRANSCRIPT_TEXT
  ATTRIBUTES CUSTOMER_ID, CALL_ID
  WAREHOUSE = SENTINEL_WH
  TARGET_LAG = '1 hour'
  AS (SELECT CALL_ID, CUSTOMER_ID, CALL_TS, TRANSCRIPT_TEXT FROM CALL_TRANSCRIPTS);

-- Semantic view: prefer CoCo's semantic-view skill in coco/PROMPTS.md.
-- Uncomment the block below only if CREATE SEMANTIC VIEW is enabled on your account.
/*
CREATE OR REPLACE SEMANTIC VIEW SENTINEL.RISK.RISK_ANALYTICS
  TABLES (
    transactions AS SENTINEL.RISK.TRANSACTIONS PRIMARY KEY (TXN_ID),
    alerts AS SENTINEL.RISK.ALERTS PRIMARY KEY (ALERT_ID),
    customers AS SENTINEL.RISK.CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
  )
  RELATIONSHIPS (
    transactions (CUSTOMER_ID) REFERENCES customers (CUSTOMER_ID),
    alerts (CUSTOMER_ID) REFERENCES customers (CUSTOMER_ID)
  )
  FACTS (
    transactions.AMOUNT_INR AS amount COMMENT = 'Transaction amount in INR',
    alerts.SCORE AS alert_score COMMENT = 'Model score 0-100'
  )
  DIMENSIONS (
    transactions.TYPOLOGY AS typology COMMENT = 'AML typology such as mule, structuring, round_trip',
    transactions.CHANNEL AS channel COMMENT = 'UPI, NEFT, IMPS, RTGS, CASH, CARD',
    customers.CITY AS city,
    customers.PEP AS is_pep COMMENT = 'Politically exposed person flag',
    alerts.STATUS AS alert_status
  )
  METRICS (
    transactions.TOTAL_AMOUNT AS SUM(transactions.AMOUNT_INR) COMMENT = 'Sum of transaction amounts',
    alerts.OPEN_ALERTS AS COUNT(alerts.ALERT_ID) COMMENT = 'Count of alerts'
  );
*/

GRANT USAGE ON DATABASE SENTINEL TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA SENTINEL.RISK TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA SENTINEL.RISK TO ROLE PUBLIC;
