-- Sentinel additive winner expansion.
-- Safe to run after 01_schema.sql, 02_seed.sql, and 03_expand.sql.
-- It never updates or deletes foundation rows. All generated IDs are deterministic.

USE DATABASE SENTINEL;
USE SCHEMA RISK;
USE WAREHOUSE SENTINEL_WH;

-- New evidence and graph surfaces. Existing tables remain unchanged.
CREATE TABLE IF NOT EXISTS DEVICE_FINGERPRINTS (
  DEVICE_ID STRING,
  CUSTOMER_ID STRING,
  IMEI_HASH STRING,
  DEVICE_MODEL STRING,
  ROOTED_FLAG BOOLEAN,
  FIRST_SEEN TIMESTAMP_TZ,
  LAST_SEEN TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS LOGIN_EVENTS (
  LOGIN_ID STRING,
  CUSTOMER_ID STRING,
  DEVICE_ID STRING,
  IP_ADDRESS STRING,
  CITY STRING,
  LATITUDE FLOAT,
  LONGITUDE FLOAT,
  LOGIN_TS TIMESTAMP_TZ,
  SUCCESS BOOLEAN
);

CREATE TABLE IF NOT EXISTS MERCHANTS (
  MERCHANT_ID STRING,
  MERCHANT_NAME STRING,
  MCC_CODE STRING,
  CITY STRING,
  CATEGORY STRING,
  RISK_LEVEL STRING
);

CREATE TABLE IF NOT EXISTS ENTITY_RELATIONSHIPS (
  FROM_ENTITY STRING,
  TO_ENTITY STRING,
  RELATIONSHIP STRING,
  WEIGHT FLOAT,
  LAST_ACTIVITY_TS TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS CASE_EVIDENCE (
  CASE_ID STRING,
  EVIDENCE_TYPE STRING,
  REFERENCE_ID STRING,
  DESCRIPTION STRING
);

CREATE TABLE IF NOT EXISTS ALERT_TRANSACTION_LINKS (
  ALERT_ID STRING,
  TXN_ID STRING,
  LINK_TYPE STRING
);

-- Expand customers from the existing foundation to 250 total.
INSERT INTO CUSTOMERS
  (CUSTOMER_ID, NAME, TYPE, PAN, CITY, KYC_STATUS, PEP, RISK_RATING, OCCUPATION, ONBOARDING_DATE)
WITH seq AS (
  SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn
  FROM TABLE(GENERATOR(ROWCOUNT => 242))
), cities AS (
  SELECT * FROM VALUES
    (0, 'Mumbai'), (1, 'Delhi'), (2, 'Ahmedabad'), (3, 'Surat'),
    (4, 'Jaipur'), (5, 'Bengaluru'), (6, 'Hyderabad'), (7, 'Chennai'),
    (8, 'Pune'), (9, 'Kochi'), (10, 'Kolkata'), (11, 'Indore'),
    (12, 'Lucknow'), (13, 'Chandigarh') AS t(idx, city)
)
SELECT
  CONCAT('CUS-WIN-', LPAD(rn::STRING, 4, '0')),
  CASE MOD(rn, 10)
    WHEN 0 THEN CONCAT('Aarohan Salary Customer ', rn)
    WHEN 1 THEN CONCAT('Aarohan MSME Customer ', rn)
    WHEN 2 THEN CONCAT('Aarohan Proprietor ', rn)
    WHEN 3 THEN CONCAT('Aarohan Partnership ', rn)
    WHEN 4 THEN CONCAT('Aarohan LLP ', rn)
    WHEN 5 THEN CONCAT('Aarohan Private Ltd ', rn)
    WHEN 6 THEN CONCAT('Aarohan Trust ', rn)
    WHEN 7 THEN CONCAT('Aarohan NGO ', rn)
    WHEN 8 THEN CONCAT('Aarohan HNW ', rn)
    ELSE CONCAT('Aarohan NRI ', rn)
  END,
  CASE MOD(rn, 10)
    WHEN 0 THEN 'salaried' WHEN 1 THEN 'self_employed' WHEN 2 THEN 'msme'
    WHEN 3 THEN 'proprietorship' WHEN 4 THEN 'partnership' WHEN 5 THEN 'llp'
    WHEN 6 THEN 'private_limited' WHEN 7 THEN 'trust' WHEN 8 THEN 'ngo' ELSE 'nri'
  END,
  CONCAT('SYNTH', LPAD(rn::STRING, 5, '0'), 'X'),
  c.city,
  CASE MOD(rn, 7) WHEN 0 THEN 'enhanced_due_diligence' WHEN 1 THEN 'pending' ELSE 'verified' END,
  MOD(rn, 29) = 0,
  CASE MOD(rn, 10) WHEN 0 THEN 'low' WHEN 1 THEN 'medium' WHEN 2 THEN 'high' WHEN 3 THEN 'critical' ELSE 'medium' END,
  CASE MOD(rn, 6) WHEN 0 THEN 'Salaried professional' WHEN 1 THEN 'MSME operator' WHEN 2 THEN 'Importer/exporter' WHEN 3 THEN 'Technology consultant' WHEN 4 THEN 'Healthcare provider' ELSE 'Retail merchant' END,
  DATEADD(day, -MOD(rn * 17, 1700), DATE '2026-08-30')
FROM seq
JOIN cities c ON c.idx = MOD(rn - 1, 14)
WHERE NOT EXISTS (
  SELECT 1 FROM CUSTOMERS x WHERE x.CUSTOMER_ID = CONCAT('CUS-WIN-', LPAD(rn::STRING, 4, '0'))
);

-- Add accounts with a deterministic one-to-many customer relationship.
INSERT INTO ACCOUNTS
  (ACCOUNT_ID, CUSTOMER_ID, PRODUCT, IFSC, OPENED_ON, BALANCE_INR, STATUS)
WITH seq AS (
  SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn
  FROM TABLE(GENERATOR(ROWCOUNT => 442))
)
SELECT
  CONCAT('ACC-WIN-', LPAD(rn::STRING, 4, '0')),
  CONCAT('CUS-WIN-', LPAD((MOD(rn - 1, 242) + 1)::STRING, 4, '0')),
  CASE MOD(rn, 6) WHEN 0 THEN 'savings' WHEN 1 THEN 'current' WHEN 2 THEN 'salary' WHEN 3 THEN 'overdraft' WHEN 4 THEN 'escrow' ELSE 'loan-linked' END,
  CONCAT('AFLN', LPAD((MOD(rn * 7919, 9999) + 1)::STRING, 4, '0')),
  DATEADD(day, -MOD(rn * 13, 1200), DATE '2026-08-30'),
  CASE WHEN MOD(rn, 17) = 0 THEN -1 * (100000 + MOD(rn * 113, 900000)) ELSE 25000 + MOD(rn * 1777, 2500000) END,
  CASE MOD(rn, 11) WHEN 0 THEN 'watch' WHEN 1 THEN 'frozen' ELSE 'active' END
FROM seq
WHERE NOT EXISTS (
  SELECT 1 FROM ACCOUNTS x WHERE x.ACCOUNT_ID = CONCAT('ACC-WIN-', LPAD(rn::STRING, 4, '0'))
);

-- 6,000 deterministic transactions over the 90-day demonstration window.
INSERT INTO TRANSACTIONS
  (TXN_ID, TXN_TS, ACCOUNT_ID, CUSTOMER_ID, COUNTERPARTY, CHANNEL, TXN_TYPE, AMOUNT_INR, CITY, IS_FRAUD, TYPOLOGY, NARRATIVE)
WITH seq AS (
  SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn
  FROM TABLE(GENERATOR(ROWCOUNT => 6000))
)
SELECT
  CONCAT('TXN-WIN-', LPAD(rn::STRING, 6, '0')),
  DATEADD(hour, MOD(rn * 7, 2160), DATEADD(day, -MOD(rn - 1, 90), TO_TIMESTAMP_TZ('2026-08-30 00:00:00 +05:30'))),
  CONCAT('ACC-WIN-', LPAD((MOD(rn - 1, 442) + 1)::STRING, 4, '0')),
  CONCAT('CUS-WIN-', LPAD((MOD(rn - 1, 242) + 1)::STRING, 4, '0')),
  CASE MOD(rn, 12)
    WHEN 0 THEN 'SALARY-CREDIT' WHEN 1 THEN 'UTILITY-BILL' WHEN 2 THEN 'RENT-SETTLEMENT'
    WHEN 3 THEN 'GST-PAYMENT' WHEN 4 THEN 'EMI-SERVICER' WHEN 5 THEN 'NEXUS DIGITAL MART'
    WHEN 6 THEN 'UPI-PEER' WHEN 7 THEN 'CASH-ATM' WHEN 8 THEN 'MERCHANT-POS'
    WHEN 9 THEN 'DUBAI-CLIENT-ALPHA' WHEN 10 THEN 'VENDOR-LOGISTICS' ELSE 'HOUSEHOLD-EXPENSE'
  END,
  CASE MOD(rn, 10) WHEN 0 THEN 'NEFT' WHEN 1 THEN 'RTGS' WHEN 2 THEN 'IMPS' WHEN 3 THEN 'UPI' WHEN 4 THEN 'CASH' WHEN 5 THEN 'ATM' WHEN 6 THEN 'POS' WHEN 7 THEN 'QR' WHEN 8 THEN 'ACH' ELSE 'NACH' END,
  CASE WHEN MOD(rn, 2) = 0 THEN 'credit' ELSE 'debit' END,
  CASE WHEN MOD(rn, 67) = 0 THEN 950000 + MOD(rn, 7) * 15000 ELSE 100 + MOD(rn * 7919, 24999900) END,
  CASE MOD(rn - 1, 14) WHEN 0 THEN 'Mumbai' WHEN 1 THEN 'Delhi' WHEN 2 THEN 'Ahmedabad' WHEN 3 THEN 'Surat' WHEN 4 THEN 'Jaipur' WHEN 5 THEN 'Bengaluru' WHEN 6 THEN 'Hyderabad' WHEN 7 THEN 'Chennai' WHEN 8 THEN 'Pune' WHEN 9 THEN 'Kochi' WHEN 10 THEN 'Kolkata' WHEN 11 THEN 'Indore' WHEN 12 THEN 'Lucknow' ELSE 'Chandigarh' END,
  MOD(rn, 67) = 0,
  CASE WHEN MOD(rn, 67) <> 0 THEN 'benign' ELSE CASE MOD(rn, 10) WHEN 0 THEN 'structuring' WHEN 1 THEN 'mule' WHEN 2 THEN 'round_trip' WHEN 3 THEN 'pep_unusual' WHEN 4 THEN 'layering' WHEN 5 THEN 'smurfing' WHEN 6 THEN 'shell_company' WHEN 7 THEN 'fake_invoice' WHEN 8 THEN 'cash_funnel' ELSE 'mule' END END,
  CASE WHEN MOD(rn, 67) <> 0 THEN 'Deterministic synthetic ordinary banking activity: salary, bill, rent, merchant, tax, or EMI flow.' ELSE 'Deterministic synthetic monitoring event generated for an explainable AML typology.' END
FROM seq
WHERE NOT EXISTS (
  SELECT 1 FROM TRANSACTIONS x WHERE x.TXN_ID = CONCAT('TXN-WIN-', LPAD(rn::STRING, 6, '0'))
);

-- Add 18 cases, 133 alerts, and an explicit alert-to-transaction evidence bridge.
INSERT INTO CASES (CASE_ID, TITLE, STATUS, OWNER, OPENED_ON, TYPOLOGY, SEVERITY, SUMMARY)
WITH seq AS (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn FROM TABLE(GENERATOR(ROWCOUNT => 18)))
SELECT CONCAT('CASE-WIN-', LPAD(rn::STRING, 4, '0')), CONCAT('Synthetic investigation case ', rn), CASE MOD(rn, 5) WHEN 0 THEN 'new' WHEN 1 THEN 'investigating' WHEN 2 THEN 'STR filed' WHEN 3 THEN 'closed' ELSE 'investigating' END, CONCAT('MLRO Analyst ', MOD(rn, 7) + 1), DATEADD(day, -MOD(rn * 3, 80), DATE '2026-08-30'), CASE MOD(rn, 8) WHEN 0 THEN 'structuring' WHEN 1 THEN 'mule' WHEN 2 THEN 'round_trip' WHEN 3 THEN 'pep_unusual' WHEN 4 THEN 'layering' WHEN 5 THEN 'shell_company' WHEN 6 THEN 'fake_invoice' ELSE 'cash_funnel' END, CASE MOD(rn, 3) WHEN 0 THEN 'medium' WHEN 1 THEN 'high' ELSE 'critical' END, 'Synthetic case with linked transactions, alerts, and governed evidence.' FROM seq
WHERE NOT EXISTS (SELECT 1 FROM CASES x WHERE x.CASE_ID = CONCAT('CASE-WIN-', LPAD(rn::STRING, 4, '0')));

INSERT INTO ALERTS (ALERT_ID, ALERT_TS, CUSTOMER_ID, ACCOUNT_ID, TITLE, TYPOLOGY, SCORE, STATUS, CASE_ID, EXPLANATION)
WITH seq AS (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn FROM TABLE(GENERATOR(ROWCOUNT => 133)))
SELECT CONCAT('ALRT-WIN-', LPAD(rn::STRING, 4, '0')), DATEADD(hour, MOD(rn * 5, 1800), DATEADD(day, -MOD(rn, 90), TO_TIMESTAMP_TZ('2026-08-30 00:00:00 +05:30'))), CONCAT('CUS-WIN-', LPAD((MOD(rn - 1, 242) + 1)::STRING, 4, '0')), CONCAT('ACC-WIN-', LPAD((MOD(rn - 1, 442) + 1)::STRING, 4, '0')), CONCAT('Synthetic ', CASE MOD(rn, 8) WHEN 0 THEN 'structuring' WHEN 1 THEN 'mule' WHEN 2 THEN 'round trip' WHEN 3 THEN 'PEP' WHEN 4 THEN 'layering' WHEN 5 THEN 'shell' WHEN 6 THEN 'invoice' ELSE 'cash funnel' END, ' alert'), CASE MOD(rn, 8) WHEN 0 THEN 'structuring' WHEN 1 THEN 'mule' WHEN 2 THEN 'round_trip' WHEN 3 THEN 'pep_unusual' WHEN 4 THEN 'layering' WHEN 5 THEN 'shell_company' WHEN 6 THEN 'fake_invoice' ELSE 'cash_funnel' END, 50 + MOD(rn * 17, 50), CASE MOD(rn, 5) WHEN 0 THEN 'open' WHEN 1 THEN 'investigating' WHEN 2 THEN 'escalated' WHEN 3 THEN 'closed' ELSE 'false_positive' END, CONCAT('CASE-WIN-', LPAD((MOD(rn - 1, 18) + 1)::STRING, 4, '0')), CONCAT('Alert is linked to TXN-WIN-', LPAD(rn::STRING, 6, '0'), ' and requires evidence-backed review.') FROM seq
WHERE NOT EXISTS (SELECT 1 FROM ALERTS x WHERE x.ALERT_ID = CONCAT('ALRT-WIN-', LPAD(rn::STRING, 4, '0')));

INSERT INTO ALERT_TRANSACTION_LINKS (ALERT_ID, TXN_ID, LINK_TYPE)
WITH seq AS (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn FROM TABLE(GENERATOR(ROWCOUNT => 133)))
SELECT CONCAT('ALRT-WIN-', LPAD(rn::STRING, 4, '0')), CONCAT('TXN-WIN-', LPAD(rn::STRING, 6, '0')), 'trigger_transaction' FROM seq
WHERE NOT EXISTS (SELECT 1 FROM ALERT_TRANSACTION_LINKS x WHERE x.ALERT_ID = CONCAT('ALRT-WIN-', LPAD(rn::STRING, 4, '0')));

-- 58 conversations, bringing the corpus to 70 with the foundation data.
INSERT INTO CALL_TRANSCRIPTS (CALL_ID, CUSTOMER_ID, CALL_TS, TRANSCRIPT_TEXT)
WITH seq AS (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn FROM TABLE(GENERATOR(ROWCOUNT => 58)))
SELECT CONCAT('CALL-WIN-', LPAD(rn::STRING, 4, '0')), CONCAT('CUS-WIN-', LPAD((MOD(rn - 1, 242) + 1)::STRING, 4, '0')), DATEADD(hour, MOD(rn * 11, 2160), DATEADD(day, -MOD(rn, 90), TO_TIMESTAMP_TZ('2026-08-30 00:00:00 +05:30'))), CASE MOD(rn, 7) WHEN 0 THEN 'RM: Please share the source-of-funds document and the beneficiary invoice. Customer: I will send the supporting records today.' WHEN 1 THEN 'Customer: The cash withdrawal happened after two in the morning because the branch was closed. RM: We need to understand the rapid onward movement.' WHEN 2 THEN 'Voice transcription: Imran first then Neha was the instruction. The caller asked the team not to escalate the payment.' WHEN 3 THEN 'RM: The Dubai consultancy needs a signed contract, tax invoice, and beneficial-owner declaration before approval.' WHEN 4 THEN 'Treasury: Wholesale runoff increased in the stress window; please confirm the HQLA buffer and contingency funding line.' WHEN 5 THEN 'Credit committee: The borrower concentration is high in CRE and collateral coverage should be refreshed before renewal.' ELSE 'Customer: Salary and utility payments are routine. RM: We have recorded the explanation and will complete KYC refresh.' END FROM seq
WHERE NOT EXISTS (SELECT 1 FROM CALL_TRANSCRIPTS x WHERE x.CALL_ID = CONCAT('CALL-WIN-', LPAD(rn::STRING, 4, '0')));

-- 27 clearly labelled synthetic chunks; the original six remain untouched.
INSERT INTO REG_DOCS (DOC_ID, TITLE, SOURCE, CLAUSE, TOPIC, EXCERPT)
WITH seq AS (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn FROM TABLE(GENERATOR(ROWCOUNT => 27)))
SELECT CONCAT('DOC-SYN-WIN-', LPAD(rn::STRING, 3, '0')), CONCAT('Synthetic demonstration: governed topic ', rn), 'Synthetic demonstration material — not authoritative regulation', CONCAT('Section ', rn), CASE MOD(rn, 9) WHEN 0 THEN 'digital_lending' WHEN 1 THEN 'outsourcing' WHEN 2 THEN 'cyber_security' WHEN 3 THEN 'governance' WHEN 4 THEN 'fraud_risk' WHEN 5 THEN 'customer_due_diligence' WHEN 6 THEN 'beneficial_ownership' WHEN 7 THEN 'fatf_guidance' ELSE 'aml_monitoring' END, 'Synthetic demonstration material only. This chunk describes an analytical control pattern and must not be presented as an authoritative regulatory requirement.' FROM seq
WHERE NOT EXISTS (SELECT 1 FROM REG_DOCS x WHERE x.DOC_ID = CONCAT('DOC-SYN-WIN-', LPAD(rn::STRING, 3, '0')));

-- Add 60 earlier observations, preserving the existing August foundation rows.
INSERT INTO LIQUIDITY_DAILY (AS_OF, LCR_PCT, NSFR_PCT, HQLA_INR_CR, WHOLESALE_RUNOFF_INR_CR, BUFFER_DAYS)
WITH seq AS (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn FROM TABLE(GENERATOR(ROWCOUNT => 60)))
SELECT DATEADD(day, -rn, DATE '2026-08-01'), 101.5 + MOD(rn * 7, 17) / 2.0, 100.2 + MOD(rn * 5, 13) / 2.0, 575 + MOD(rn * 19, 130), 105 + MOD(rn * 23, 75), 20 + MOD(rn, 16) FROM seq
WHERE NOT EXISTS (SELECT 1 FROM LIQUIDITY_DAILY x WHERE x.AS_OF = DATEADD(day, -rn, DATE '2026-08-01'));

-- Add 108 borrowers. Amounts keep the existing INR convention; the view computes concentration.
INSERT INTO CREDIT_EXPOSURES (CUSTOMER_ID, CUSTOMER_NAME, EXPOSURE_INR, SECTOR)
WITH seq AS (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn FROM TABLE(GENERATOR(ROWCOUNT => 108)))
SELECT CONCAT('BOR-WIN-', LPAD(rn::STRING, 4, '0')), CONCAT('Synthetic borrower ', rn), 100000000 + MOD(rn * 271828, 180000000), CASE MOD(rn, 12) WHEN 0 THEN 'CRE' WHEN 1 THEN 'MSME' WHEN 2 THEN 'MANUFACTURING' WHEN 3 THEN 'AGRICULTURE' WHEN 4 THEN 'LOGISTICS' WHEN 5 THEN 'HEALTHCARE' WHEN 6 THEN 'NBFC' WHEN 7 THEN 'RETAIL' WHEN 8 THEN 'INFRASTRUCTURE' WHEN 9 THEN 'RENEWABLE_ENERGY' WHEN 10 THEN 'EDUCATION' ELSE 'HOSPITALITY' END FROM seq
WHERE NOT EXISTS (SELECT 1 FROM CREDIT_EXPOSURES x WHERE x.CUSTOMER_ID = CONCAT('BOR-WIN-', LPAD(rn::STRING, 4, '0')));

-- Evidence graph seed data.
INSERT INTO MERCHANTS
SELECT v.MERCHANT_ID, v.MERCHANT_NAME, v.MCC_CODE, v.CITY, v.CATEGORY, v.RISK_LEVEL
FROM VALUES
  ('MER-0001', 'Nexus Digital Mart', '5732', 'Hyderabad', 'digital_goods', 'high'),
  ('MER-0002', 'UPI Rent Hub', '6513', 'Mumbai', 'rental', 'medium'),
  ('MER-0003', 'Amrit Trading Co', '5099', 'Delhi', 'wholesale', 'medium')
  AS v(MERCHANT_ID, MERCHANT_NAME, MCC_CODE, CITY, CATEGORY, RISK_LEVEL)
WHERE NOT EXISTS (SELECT 1 FROM MERCHANTS x WHERE x.MERCHANT_ID = v.MERCHANT_ID);

INSERT INTO DEVICE_FINGERPRINTS
SELECT CONCAT('DEV-WIN-', LPAD(rn::STRING, 4, '0')), CONCAT('CUS-WIN-', LPAD((MOD(rn - 1, 242) + 1)::STRING, 4, '0')), CONCAT('IMEI-SYN-', LPAD(rn::STRING, 8, '0')), CASE MOD(rn, 4) WHEN 0 THEN 'Android A54' WHEN 1 THEN 'iPhone 13' WHEN 2 THEN 'Android S23' ELSE 'Pixel 8' END, MOD(rn, 23) = 0, TO_TIMESTAMP_TZ('2026-06-01 00:00:00 +05:30'), TO_TIMESTAMP_TZ('2026-08-30 23:00:00 +05:30') FROM (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn FROM TABLE(GENERATOR(ROWCOUNT => 242))) s
WHERE NOT EXISTS (SELECT 1 FROM DEVICE_FINGERPRINTS x WHERE x.DEVICE_ID = CONCAT('DEV-WIN-', LPAD(rn::STRING, 4, '0')));

INSERT INTO ENTITY_RELATIONSHIPS
SELECT CONCAT('CUS-WIN-', LPAD(rn::STRING, 4, '0')), CONCAT('DEV-WIN-', LPAD((MOD(rn, 242) + 1)::STRING, 4, '0')), 'shares_device', 0.5 + MOD(rn, 5) / 10.0, TO_TIMESTAMP_TZ('2026-08-30 18:00:00 +05:30') FROM (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn FROM TABLE(GENERATOR(ROWCOUNT => 242))) s
WHERE NOT EXISTS (SELECT 1 FROM ENTITY_RELATIONSHIPS x WHERE x.FROM_ENTITY = CONCAT('CUS-WIN-', LPAD(rn::STRING, 4, '0')) AND x.RELATIONSHIP = 'shares_device');

INSERT INTO CASE_EVIDENCE
SELECT CONCAT('CASE-WIN-', LPAD(rn::STRING, 4, '0')), CASE MOD(rn, 3) WHEN 0 THEN 'transaction' WHEN 1 THEN 'call' ELSE 'alert' END, CASE MOD(rn, 3) WHEN 0 THEN CONCAT('TXN-WIN-', LPAD(rn::STRING, 6, '0')) WHEN 1 THEN CONCAT('CALL-WIN-', LPAD(rn::STRING, 4, '0')) ELSE CONCAT('ALRT-WIN-', LPAD(rn::STRING, 4, '0')) END, 'Deterministic evidence reference for case investigation.' FROM (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS rn FROM TABLE(GENERATOR(ROWCOUNT => 18))) s
WHERE NOT EXISTS (SELECT 1 FROM CASE_EVIDENCE x WHERE x.CASE_ID = CONCAT('CASE-WIN-', LPAD(rn::STRING, 4, '0')));

-- Additive derived surfaces for Analyst and dashboard queries.
CREATE OR REPLACE VIEW CUSTOMER_BEHAVIOR_PROFILE AS
SELECT CUSTOMER_ID, AVG(AMOUNT_INR) AS AVG_TRANSACTION_AMOUNT, SUM(AMOUNT_INR) / 3 AS AVG_MONTHLY_VOLUME, AVG(IFF(CHANNEL IN ('CASH', 'ATM'), 1, 0)) AS AVG_CASH_RATIO, AVG(IFF(CHANNEL IN ('UPI', 'QR'), 1, 0)) AS AVG_UPI_RATIO, AVG(HOUR(TXN_TS)) AS ACTIVE_HOURS, COUNT(DISTINCT COUNTERPARTY) AS AVG_COUNTERPARTIES, MODE(HOUR(TXN_TS)) AS SALARY_DAY, AVG(AMOUNT_INR) * 3 AS ANOMALY_THRESHOLD FROM TRANSACTIONS GROUP BY CUSTOMER_ID;

CREATE OR REPLACE VIEW TRANSACTION_FEATURES AS
SELECT t.*, COUNT(*) OVER (PARTITION BY CUSTOMER_ID ORDER BY TXN_TS RANGE BETWEEN INTERVAL '10 MINUTES' PRECEDING AND CURRENT ROW) AS TRANSACTIONS_LAST_10M, COUNT(*) OVER (PARTITION BY CUSTOMER_ID ORDER BY TXN_TS RANGE BETWEEN INTERVAL '1 HOUR' PRECEDING AND CURRENT ROW) AS TRANSACTIONS_LAST_HOUR, IFF(CHANNEL IN ('CASH', 'ATM') AND TXN_TYPE = 'debit', AMOUNT_INR, 0) AS CASH_VELOCITY, COUNT(DISTINCT COUNTERPARTY) OVER (PARTITION BY CUSTOMER_ID) AS UNIQUE_COUNTERPARTIES_24H, IFF(HOUR(TXN_TS) < 6 OR HOUR(TXN_TS) >= 23, TRUE, FALSE) AS NIGHT_TRANSACTION_FLAG, IFF(DAYOFWEEK(TXN_TS) IN (0, 6), TRUE, FALSE) AS WEEKEND_FLAG, AMOUNT_INR / NULLIF(AVG(AMOUNT_INR) OVER (PARTITION BY CUSTOMER_ID), 0) AS AMOUNT_VS_CUSTOMER_AVERAGE, IFF(IS_FRAUD, 90, LEAST(89, 10 + MOD(ABS(HASH(TXN_ID)), 80))) AS ANOMALY_SCORE FROM TRANSACTIONS t;

CREATE OR REPLACE VIEW CREDIT_CONCENTRATION_VIEW AS
SELECT CUSTOMER_ID, CUSTOMER_NAME, SECTOR, EXPOSURE_INR, ROUND(100 * EXPOSURE_INR / NULLIF(SUM(EXPOSURE_INR) OVER (), 0), 2) AS PCT_OF_BOOK, ROW_NUMBER() OVER (ORDER BY EXPOSURE_INR DESC) AS EXPOSURE_RANK, SUM(EXPOSURE_INR) OVER (PARTITION BY SECTOR) AS SECTOR_EXPOSURE, IFF(ROW_NUMBER() OVER (ORDER BY EXPOSURE_INR DESC) <= 10, TRUE, FALSE) AS TOP10_EXPOSURE FROM CREDIT_EXPOSURES;

CREATE OR REPLACE VIEW LIQUIDITY_STRESS_VIEW AS
SELECT AS_OF, LCR_PCT, NSFR_PCT, HQLA_INR_CR, WHOLESALE_RUNOFF_INR_CR, BUFFER_DAYS, AVG(LCR_PCT) OVER (ORDER BY AS_OF ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ROLLING_AVG_LCR, AVG(NSFR_PCT) OVER (ORDER BY AS_OF ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ROLLING_AVG_NSFR, WHOLESALE_RUNOFF_INR_CR - LAG(WHOLESALE_RUNOFF_INR_CR) OVER (ORDER BY AS_OF) AS RUNOFF_GROWTH, HQLA_INR_CR / NULLIF(WHOLESALE_RUNOFF_INR_CR, 0) AS HQLA_COVERAGE_RATIO, HQLA_INR_CR - WHOLESALE_RUNOFF_INR_CR AS STRESS_GAP, IFF(LCR_PCT < 100 OR NSFR_PCT < 100, TRUE, FALSE) AS BREACH_FLAG FROM LIQUIDITY_DAILY;

-- CREATE OR REPLACE AGENT resets object-level grants, so restore the app role last.
GRANT USAGE ON AGENT SENTINEL.RISK.SENTINEL_AGENT TO ROLE APP_DEVELOPER;
GRANT SELECT ON SEMANTIC VIEW SENTINEL.RISK.RISK_ANALYTICS TO ROLE APP_DEVELOPER;
GRANT USAGE ON CORTEX SEARCH SERVICE SENTINEL.RISK.REG_DOC_SEARCH TO ROLE APP_DEVELOPER;
GRANT USAGE ON CORTEX SEARCH SERVICE SENTINEL.RISK.CALL_SEARCH TO ROLE APP_DEVELOPER;

SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CUSTOMERS
UNION ALL SELECT 'ACCOUNTS', COUNT(*) FROM ACCOUNTS
UNION ALL SELECT 'TRANSACTIONS', COUNT(*) FROM TRANSACTIONS
UNION ALL SELECT 'ALERTS', COUNT(*) FROM ALERTS
UNION ALL SELECT 'CASES', COUNT(*) FROM CASES
UNION ALL SELECT 'CALL_TRANSCRIPTS', COUNT(*) FROM CALL_TRANSCRIPTS
UNION ALL SELECT 'REG_DOCS', COUNT(*) FROM REG_DOCS
UNION ALL SELECT 'LIQUIDITY_DAILY', COUNT(*) FROM LIQUIDITY_DAILY
UNION ALL SELECT 'CREDIT_EXPOSURES', COUNT(*) FROM CREDIT_EXPOSURES;
