-- App read helpers for Sentinel Next.js (run after seed + expansion)
USE DATABASE SENTINEL;
USE SCHEMA RISK;
USE WAREHOUSE SENTINEL_WH;

CREATE OR REPLACE VIEW OPEN_ALERTS_V AS
SELECT *
FROM ALERTS
WHERE LOWER(STATUS) IN ('open', 'investigating', 'escalated');

CREATE OR REPLACE VIEW CASE_CUSTOMERS_V AS
SELECT CASE_ID, CUSTOMER_ID
FROM (
  SELECT DISTINCT CASE_ID, CUSTOMER_ID
  FROM ALERTS
  WHERE CASE_ID IS NOT NULL AND CUSTOMER_ID IS NOT NULL
);

GRANT SELECT ON VIEW OPEN_ALERTS_V TO ROLE APP_DEVELOPER;
GRANT SELECT ON VIEW CASE_CUSTOMERS_V TO ROLE APP_DEVELOPER;

-- Demo warmup: run 2 minutes before recording
-- SELECT 1;
-- SELECT COUNT(*) FROM OPEN_ALERTS_V;
-- ALTER WAREHOUSE SENTINEL_WH SET AUTO_SUSPEND = 120;
