-- Optional: run once if expansion/seed scripts were applied multiple times.
-- Keeps the newest row per natural key. Review counts before/after in a worksheet.

USE DATABASE SENTINEL;
USE SCHEMA RISK;

-- Preview duplicate call ids
-- SELECT CALL_ID, COUNT(*) FROM CALL_TRANSCRIPTS GROUP BY CALL_ID HAVING COUNT(*) > 1;

CREATE OR REPLACE TABLE CALL_TRANSCRIPTS AS
SELECT CALL_ID, CUSTOMER_ID, CALL_TS, TRANSCRIPT_TEXT
FROM CALL_TRANSCRIPTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY CALL_ID ORDER BY CALL_TS DESC) = 1;

CREATE OR REPLACE TABLE ALERTS AS
SELECT *
FROM ALERTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ALERT_ID ORDER BY ALERT_TS DESC) = 1;

CREATE OR REPLACE TABLE TRANSACTIONS AS
SELECT TXN_ID, TXN_TS, ACCOUNT_ID, CUSTOMER_ID, COUNTERPARTY, CHANNEL, TXN_TYPE,
       AMOUNT_INR, CITY, IS_FRAUD, TYPOLOGY, NARRATIVE
FROM TRANSACTIONS
QUALIFY ROW_NUMBER() OVER (PARTITION BY TXN_ID ORDER BY TXN_TS DESC) = 1;
