-- Run as ACCOUNTADMIN after agent deploy (CREATE OR REPLACE AGENT drops USAGE grants).
-- Shared app login: SENTINEL_DEV_USER with role APP_DEVELOPER.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SENTINEL_WH;

-- Warehouse/database grants are usually set at bootstrap; skip if your admin role cannot re-grant WH.
-- GRANT USAGE, OPERATE ON WAREHOUSE SENTINEL_WH TO ROLE APP_DEVELOPER;

GRANT USAGE ON DATABASE SENTINEL TO ROLE APP_DEVELOPER;
GRANT USAGE ON SCHEMA SENTINEL.RISK TO ROLE APP_DEVELOPER;

GRANT SELECT ON ALL TABLES IN SCHEMA SENTINEL.RISK TO ROLE APP_DEVELOPER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SENTINEL.RISK TO ROLE APP_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SENTINEL.RISK TO ROLE APP_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SENTINEL.RISK TO ROLE APP_DEVELOPER;

GRANT INSERT ON TABLE SENTINEL.RISK.COPILOT_AUDIT TO ROLE APP_DEVELOPER;

GRANT USAGE ON AGENT SENTINEL.RISK.SENTINEL_AGENT TO ROLE APP_DEVELOPER;
GRANT SELECT ON SEMANTIC VIEW SENTINEL.RISK.RISK_ANALYTICS TO ROLE APP_DEVELOPER;
GRANT USAGE ON CORTEX SEARCH SERVICE SENTINEL.RISK.REG_DOC_SEARCH TO ROLE APP_DEVELOPER;
GRANT USAGE ON CORTEX SEARCH SERVICE SENTINEL.RISK.CALL_SEARCH TO ROLE APP_DEVELOPER;

-- Optional: ensure shared dev user has the app role (safe if user already exists).
GRANT ROLE APP_DEVELOPER TO USER SENTINEL_DEV_USER;

SELECT 'APP_DEVELOPER grants applied' AS STATUS;
