-- Restore Golden Peak ~11.4% book overlay after winner expansion dilutes concentrations.
-- Run as ACCOUNTADMIN (or role with UPDATE on CREDIT_EXPOSURES).

USE DATABASE SENTINEL;
USE SCHEMA RISK;

UPDATE SENTINEL.RISK.CREDIT_EXPOSURES
SET EXPOSURE_INR = (
  SELECT SUM(EXPOSURE_INR) * 0.114 / 0.886
  FROM SENTINEL.RISK.CREDIT_EXPOSURES
  WHERE CUSTOMER_ID <> 'CUS-1304'
)
WHERE CUSTOMER_ID = 'CUS-1304';

CREATE OR REPLACE VIEW CREDIT_CONCENTRATION_VIEW AS
WITH deduped AS (
  SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MAX(SECTOR) AS SECTOR,
    MAX(EXPOSURE_INR) AS EXPOSURE_INR
  FROM CREDIT_EXPOSURES
  GROUP BY CUSTOMER_ID, CUSTOMER_NAME
),
scored AS (
  SELECT
    *,
    ROUND(100 * EXPOSURE_INR / NULLIF(SUM(EXPOSURE_INR) OVER (), 0), 2) AS PCT_OF_BOOK
  FROM deduped
)
SELECT
  CUSTOMER_ID,
  CUSTOMER_NAME,
  SECTOR,
  EXPOSURE_INR,
  PCT_OF_BOOK,
  ROW_NUMBER() OVER (ORDER BY EXPOSURE_INR DESC) AS EXPOSURE_RANK,
  SUM(EXPOSURE_INR) OVER (PARTITION BY SECTOR) AS SECTOR_EXPOSURE,
  IFF(ROW_NUMBER() OVER (ORDER BY EXPOSURE_INR DESC) <= 10, TRUE, FALSE) AS TOP10_EXPOSURE,
  IFF(PCT_OF_BOOK >= 10.0, TRUE, FALSE) AS BREACH_FLAG
FROM scored;

SELECT CUSTOMER_NAME, PCT_OF_BOOK, BREACH_FLAG
FROM CREDIT_CONCENTRATION_VIEW
WHERE CUSTOMER_ID = 'CUS-1304';
